- hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Generate SSL certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt creates=/etc/ssl/private/nginx-selfsigned.key

    - name: Copy custom Nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
